assignment5/config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :posts
end

assignment5/app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
end

assignment5/app/models/user.rb
class User < ActiveRecord::Base
  has_many :post
end

assignment5/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

assignment5/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
   @posts = Post.all
  end

  def show
    @post = Post.find_by_id(params[:id])
  end

  def edit
    @post = Post.find_by_id(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(params[:post])
    end

  def destroy
    @post = Post.find_by_id(params[:id])
    @post.destroy
    flash[:notice] = "This post was deleted"
    redirect_to posts_path
  end
end

assignment5/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      flash[:notice] = "Your user profile was saved"
      redirect_to action: "index"
    else
    end
  end

  def show
    @user = User.find_by_id(params[:id])
  end

  def edit
    @user = User.find_by_id(params[:id])
  end

  def update
    @user = User.find_by_id(params[:id])

    if @user.update_attributes(params[:user])
      flash[:notice] = "Your profile was updated!"
      redirect_to action: "show"
    else
    end
  end


end

assignment5/app/helpers/application_helper.rb
module ApplicationHelper
end

assignment5/app/helpers/user_helper.rb
module UserHelper
end

assignment5/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Assignment5</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

assignment5/app/views/posts/edit.html.erb
<h1> Edit your post:</h1>

<%= form_for @post, url: {action: "update"} do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br/>
  <%= f.label :body %>
  <%= f.text_field :body %>
  <br/>
  <%= f.submit "Click here to update" %>
<% end %>

assignment5/app/views/posts/index.html.erb
<h1>Here are all the posts:</h1>
<% @posts.each do |post| %>
  <ul>
    <li><%= link_to post.title, post_path(post) %></li>
    <p>By <%= post.user.name %>
  </ul>
<% end %>

assignment5/app/views/posts/new.html.erb
<h1>Write a new post:</h1>

<%= form_for @post, url: {action: "create"} do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br/>
  <%= f.label :body %>
  <%= f.text_field :body %>
  <br/>
  <%= f.submit "Publish your post" %>
<% end %>

assignment5/app/views/posts/show.html.erb
<h1>A single post:</h1>
<h2><%= @post.title %></h2>
<h3>By <%= @post.user.name %></h3>
<p><%= @post.body %></p>

<%= link_to "Edit this post", edit_post_path(@post) %>
<%= link_to "Delete this post", post_path(@post) %>

assignment5/app/views/users/edit.html.erb
<h1> Edit your information:</h1>

<%= form_for @user, url: {action: "update"} do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br/>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <br/>
  <%= f.label :city %>
  <%= f.text_field :city %>
  <br/>
  <%= f.label :state %>
  <%= f.text_field :state %>
  <br/>
  <%= f.submit "Click here to update" %>
<% end %>

assignment5/app/views/users/index.html.erb
<h1>Index of users:</h1>

<% @users.each do |user| %>
  <ul>
    <li><%= link_to user.name, user_path(user) %></li>
  </ul>
<% end %>

assignment5/app/views/users/new.html.erb
<h1>Set up new profile:</h1>

<%= form_for @user, url: {action: "create"} do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br/>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <br/>
  <%= f.label :city %>
  <%= f.text_field :city %>
  <br/>
  <%= f.label :state %>
  <%= f.text_field :state %>
  <br/>
  <%= f.submit "Add new profile" %>
<% end %>

assignment5/app/views/users/show.html.erb
<h1>Information for each User:</h1>
<ul>
  <li>User Id: <%= @user.id %></li>
  <li>Name: <%= @user.name%></li>
  <li>Email: <%= @user.email %></li>
  <li>City: <%= @user.city %></li>
  <li>State: <%= @user.state %></li>
</ul>

<%= link_to "Edit your information", edit_user_path(@user) %>